### ISSUE TITLE
Saving and compiling a .SCSS file causes live reload of previous, not current, .css styles

### ISSUE THREAD

**Issue by szalapski** [jsakamoto/Toolbelt.AspNetCore.CssLiveReloader#5]
When I save app.scss file in Visual Studio the Web Compiler extension immediately compiles it in the background, and I see "Done" in the status bar...

Expected behavior: CssLiveReloader detects the changed app.min.css file and loads it, showing me new styles.

Actual behavior: CssLiveReloader loads the _previous_ CSS file, showing me almost-correct styles.  I need to make a spurious change and re-save to make  Web Compiler compile one more time. CssLiveReloader again loads the _previous_ CSS file, which is the same as the current one.

Any idea how to fix this?

**Comment by jsakamoto** [comment]
@szalapski Thanks for reporting.

I tried to reproduce your problem on my hand, but unfortunately, I couldn't.

So to isolate the cause of the problem, could you try to disable the cache of the web browser by using the developer console and rerun it?
![image](https://user-images.githubusercontent.com/95908/129445211-7a4de9a8-ae69-4fe0-8fc9-4c6ed2224265.png)

If the problem was resolved when the cache was disabled, I might be able to improve controlling the browser cache in this library.

**Comment by szalapski** [comment]
I have stopped using this piece and instead I use the built-in .NET 5/6 way. Thanks though!
